plugin:
    name: 'algad.bootstrap::lang.plugin.name'
    description: 'algad.bootstrap::lang.plugin.description'
    author: algad
    icon: oc-icon-flask
    homepage: 'https://github.com/Alexandre-Gadiou/OctoberCMS-Bootstrap'
permissions:
    algad.bootstrap.manage_events:
        tab: 'algad.bootstrap::lang.plugin.name'
        label: 'algad.bootstrap::lang.manage_events'
navigation:
    calendar:
        label: 'algad.bootstrap::lang.menu.calendar'
        url: algad/bootstrap/events
        icon: icon-calendar
        permissions:
            - algad.bootstrap.manage_events
        sideMenu:
            events:
                label: 'algad.bootstrap::lang.menu.events'
                url: algad/bootstrap/events
                icon: icon-tag
