title: Events
modelClass: Algad\Bootstrap\Models\Event
list: $/algad/bootstrap/models/event/columns.yaml
recordUrl: 'algad/bootstrap/events/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
